runtime: java21
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_instances: 1
  max_instances: 3
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 5000ms
  max_pending_latency: 10000ms
  max_concurrent_requests: 80
entrypoint: python src/trackcase_service/main.py
