"""0000002

Revision ID: 05f45a6433b2
Revises: 4da10b509bf9
Create Date: 2023-12-23 14:06:17.123543

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05f45a6433b2"
down_revision: Union[str, None] = "4da10b509bf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("form_form_status_id_fkey", "form", type_="foreignkey")
    op.drop_constraint(
        "history_form_form_status_id_fkey", "history_form", type_="foreignkey"
    )
    op.drop_column("form", "form_status_id")
    op.drop_column("history_form", "form_status_id")
    op.drop_table("form_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history_form",
        sa.Column("form_status_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "history_form_form_status_id_fkey",
        "history_form",
        "form_status",
        ["form_status_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "form",
        sa.Column("form_status_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "form_form_status_id_fkey",
        "form",
        "form_status",
        ["form_status_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "form_status",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=3000), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="form_status_pkey"),
        sa.UniqueConstraint("name", name="form_status_name_key"),
    )
    # ### end Alembic commands ###
