"""Add Court and Judge

Revision ID: 3a244a617255
Revises: 4255e117d715
Create Date: 2023-09-16 17:39:24.074983

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a244a617255"
down_revision: Union[str, None] = "4255e117d715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "court",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("dhs_address", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("dhs_address"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "judge",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("webex", sa.String(length=100), nullable=True),
        sa.Column("court_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["court_id"], ["court.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("webex"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("judge")
    op.drop_table("court")
    # ### end Alembic commands ###
