"""Database Init

Revision ID: 4255e117d715
Revises:
Create Date: 2023-09-16 16:50:54.477657

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4255e117d715"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_type",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "collection_method",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "form_status",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "form_type",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "hearing_type",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "task_type",
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("sysdate"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_type")
    op.drop_table("hearing_type")
    op.drop_table("form_type")
    op.drop_table("form_status")
    op.drop_table("collection_method")
    op.drop_table("case_type")
    # ### end Alembic commands ###
