"""0000002

Revision ID: 6611a53564c1
Revises: e0d428e39e39
Create Date: 2024-02-04 09:29:26.302544

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6611a53564c1'
down_revision: Union[str, None] = 'e0d428e39e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('form_task_calendar_id_fkey', 'form', type_='foreignkey')
    op.drop_column('form', 'task_calendar_id')
    op.add_column('history_task_calendar', sa.Column('form_id', sa.Integer(), nullable=True))
    op.drop_constraint('history_task_calendar_court_case_id_fkey', 'history_task_calendar', type_='foreignkey')
    op.create_foreign_key(None, 'history_task_calendar', 'form', ['form_id'], ['id'], onupdate='NO ACTION', ondelete='RESTRICT')
    op.drop_column('history_task_calendar', 'court_case_id')
    op.add_column('task_calendar', sa.Column('form_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_calendar_court_case_id_fkey', 'task_calendar', type_='foreignkey')
    op.create_foreign_key(None, 'task_calendar', 'form', ['form_id'], ['id'], onupdate='NO ACTION', ondelete='RESTRICT')
    op.drop_column('task_calendar', 'court_case_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_calendar', sa.Column('court_case_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_calendar', type_='foreignkey')
    op.create_foreign_key('task_calendar_court_case_id_fkey', 'task_calendar', 'court_case', ['court_case_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('task_calendar', 'form_id')
    op.add_column('history_task_calendar', sa.Column('court_case_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'history_task_calendar', type_='foreignkey')
    op.create_foreign_key('history_task_calendar_court_case_id_fkey', 'history_task_calendar', 'court_case', ['court_case_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('history_task_calendar', 'form_id')
    op.add_column('form', sa.Column('task_calendar_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('form_task_calendar_id_fkey', 'form', 'task_calendar', ['task_calendar_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
