"""third

Revision ID: 7e7707fe5725
Revises: a2a9b049b116
Create Date: 2023-12-10 11:46:52.921343

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7e7707fe5725"
down_revision: Union[str, None] = "a2a9b049b116"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
