"""third

Revision ID: 8a33d9c1512a
Revises: 8d07c1a3dc17
Create Date: 2024-02-18 09:09:01.694307

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a33d9c1512a'
down_revision: Union[str, None] = '8d07c1a3dc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_collection', 'quote_date')
    op.drop_column('cash_collection', 'status')
    op.drop_column('cash_collection', 'comments')
    op.drop_column('history_case_collection', 'quote_date')
    op.drop_column('history_cash_collection', 'status')
    op.drop_column('history_cash_collection', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_cash_collection', sa.Column('comments', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.add_column('history_cash_collection', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('history_case_collection', sa.Column('quote_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cash_collection', sa.Column('comments', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.add_column('cash_collection', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('case_collection', sa.Column('quote_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
