"""0000002

Revision ID: 8d07c1a3dc17
Revises: 97637fd7cae7
Create Date: 2024-02-13 22:42:00.006742

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d07c1a3dc17"
down_revision: Union[str, None] = "97637fd7cae7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "case_collection",
        "quote_amount",
        existing_type=sa.BIGINT(),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "cash_collection",
        "collected_amount",
        existing_type=sa.BIGINT(),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "cash_collection",
        "waived_amount",
        existing_type=sa.BIGINT(),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "history_case_collection",
        "quote_amount",
        existing_type=sa.BIGINT(),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "collected_amount",
        existing_type=sa.BIGINT(),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "waived_amount",
        existing_type=sa.BIGINT(),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "history_cash_collection",
        "waived_amount",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "collected_amount",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history_case_collection",
        "quote_amount",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "cash_collection",
        "waived_amount",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "cash_collection",
        "collected_amount",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "case_collection",
        "quote_amount",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
