"""first

Revision ID: 97637fd7cae7
Revises:
Create Date: 2024-02-05 23:42:50.572015

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a33d9c1512a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "collection_method",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "court",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("dhs_address", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "form_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "hearing_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "task_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "history_court",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("court_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("dhs_address", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["court.id"],
            name="history_court_court_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "judge",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("webex", sa.String(length=1000), nullable=True),
        sa.Column("court_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["court.id"],
            name="judge_court_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("webex"),
    )
    op.create_table(
        "client",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("a_number", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("judge_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["judge_id"],
            ["judge.id"],
            name="client_judge_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("a_number"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "history_judge",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("webex", sa.String(length=1000), nullable=True),
        sa.Column("court_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["court.id"],
            name="history_judge_court_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["judge_id"],
            ["judge.id"],
            name="history_judge_judge_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "court_case",
        sa.Column("case_type_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_type_id"],
            ["case_type.id"],
            name="court_case_case_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name="court_case_client_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_client",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("a_number", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("judge_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name="history_client_client_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["judge_id"],
            ["judge.id"],
            name="history_client_judge_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "case_collection",
        sa.Column("quote_amount", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="case_collection_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("court_case_id"),
    )
    op.create_table(
        "form",
        sa.Column("submit_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_number", sa.String(length=100), nullable=True),
        sa.Column("priority_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_submit_date", sa.DateTime(), nullable=True),
        sa.Column("decision_date", sa.DateTime(), nullable=True),
        sa.Column("form_type_id", sa.Integer(), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="form_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["form_type_id"],
            ["form_type.id"],
            name="form_form_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hearing_calendar",
        sa.Column("hearing_date", sa.DateTime(), nullable=False),
        sa.Column("hearing_type_id", sa.Integer(), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="hearing_calendar_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_type_id"],
            ["hearing_type.id"],
            name="hearing_calendar_hearing_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("court_case_id"),
    )
    op.create_table(
        "history_court_case",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("case_type_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_type_id"],
            ["case_type.id"],
            name="history_court_case_case_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name="history_court_case_client_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_court_case_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cash_collection",
        sa.Column("collection_date", sa.DateTime(), nullable=False),
        sa.Column("collected_amount", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("waived_amount", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("memo", sa.String(length=3000), nullable=False),
        sa.Column("case_collection_id", sa.Integer(), nullable=False),
        sa.Column("collection_method_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_collection_id"],
            ["case_collection.id"],
            name="cash_collection_case_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_method_id"],
            ["collection_method.id"],
            name="cash_collection_collection_method_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_case_collection",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("case_collection_id", sa.Integer(), nullable=False),
        sa.Column("quote_amount", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("court_case_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_collection_id"],
            ["case_collection.id"],
            name="history_case_collection_case_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_case_collection_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_hearing_calendar",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("hearing_calendar_id", sa.Integer(), nullable=False),
        sa.Column("hearing_date", sa.DateTime(), nullable=True),
        sa.Column("hearing_type_id", sa.Integer(), nullable=True),
        sa.Column("court_case_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_hearing_calendar_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_calendar_id"],
            ["hearing_calendar.id"],
            name="history_hearing_calendar_hearing_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_type_id"],
            ["hearing_type.id"],
            name="history_hearing_calendar_hearing_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_calendar",
        sa.Column("task_date", sa.DateTime(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("task_type_id", sa.Integer(), nullable=False),
        sa.Column("hearing_calendar_id", sa.Integer(), nullable=True),
        sa.Column("form_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form.id"],
            name="task_calendar_form_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_calendar_id"],
            ["hearing_calendar.id"],
            name="task_calendar_hearing_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"],
            ["task_type.id"],
            name="task_calendar_task_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_cash_collection",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("cash_collection_id", sa.Integer(), nullable=False),
        sa.Column("collection_date", sa.DateTime(), nullable=True),
        sa.Column("collected_amount", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("waived_amount", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("memo", sa.String(length=3000), nullable=True),
        sa.Column("case_collection_id", sa.Integer(), nullable=True),
        sa.Column("collection_method_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_collection_id"],
            ["case_collection.id"],
            name="history_cash_collection_case_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cash_collection_id"],
            ["cash_collection.id"],
            name="history_cash_collection_cash_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_method_id"],
            ["collection_method.id"],
            name="history_cash_collection_collection_method_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_form",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("submit_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_number", sa.String(length=100), nullable=True),
        sa.Column("priority_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_submit_date", sa.DateTime(), nullable=True),
        sa.Column("decision_date", sa.DateTime(), nullable=True),
        sa.Column("form_type_id", sa.Integer(), nullable=True),
        sa.Column("court_case_id", sa.Integer(), nullable=True),
        sa.Column("task_calendar_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_form_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form.id"],
            name="history_form_form_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["form_type_id"],
            ["form_type.id"],
            name="history_form_form_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_calendar_id"],
            ["task_calendar.id"],
            name="history_form_task_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_task_calendar",
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("task_calendar_id", sa.Integer(), nullable=False),
        sa.Column("task_date", sa.DateTime(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("task_type_id", sa.Integer(), nullable=True),
        sa.Column("hearing_calendar_id", sa.Integer(), nullable=True),
        sa.Column("form_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form.id"],
            name="history_task_calendar_form_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_calendar_id"],
            ["hearing_calendar.id"],
            name="history_task_calendar_hearing_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_calendar_id"],
            ["task_calendar.id"],
            name="history_task_calendar_task_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"],
            ["task_type.id"],
            name="history_task_calendar_task_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # other migrations
    # add partial constraints
    op.execute(
        """CREATE UNIQUE INDEX task_calendar_hearing_calendar_id_1 ON task_calendar (hearing_calendar_id) WHERE hearing_calendar_id IS NOT NULL"""  # noqa: E501
    )
    op.execute(
        """CREATE UNIQUE INDEX task_calendar_form_id_1 ON task_calendar (form_id) WHERE form_id IS NOT NULL"""  # noqa: E501
    )
    op.create_index(
        "task_calendar_hearing_calendar_id_1",
        "task_calendar",
        ["hearing_calendar_id"],
        unique=False,
        postgresql_where="(hearing_calendar_id IS NOT NULL)",
    )
    op.create_index(
        "task_calendar_form_id_1",
        "task_calendar",
        ["form_id"],
        unique=False,
        postgresql_where="(form_id IS NOT NULL)",
    )
    # insert test data
    op.execute(
        """INSERT INTO case_type (created, modified, name, description) VALUES (now(), now(), 'ASYLUM', 'FILING FOR ASYLUM WITH USCIS, EOIR or BOARD OF IMMIGRATION APPEALS')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO case_type (created, modified, name, description) VALUES (now(), now(), 'TPS', 'FILING FOR TEMPORARY PROTECTED STATUS WITH USCIS, EOIR or BOARD OF IMMIGRATION APPEALS')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description) VALUES (now(), now(), 'ZELLE', 'PAID WITH ZELLE TRANSFER')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description) VALUES (now(), now(), 'MONEY ORDER', 'PAID WITH MONEY ORDER')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description) VALUES (now(), now(), 'CHECK', 'PAID WITH PERSONAL CHECK')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description) VALUES (now(), now(), 'CASH', 'PAID WITH CASH')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO form_type (created, modified, name, description) VALUES (now(), now(), 'I-589', 'APPLICATION FOR ASYLUM AND FOR WITHHOLDING OF REMOVAL')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO form_type (created, modified, name, description) VALUES (now(), now(), 'I-821', 'APPLICATION FOR TEMPORARY PROTECTED STATUS')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO form_type (created, modified, name, description) VALUES (now(), now(), 'I-765', 'APPLICATION FOR EMPLOYMENT AUTHORIZATION')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO hearing_type (created, modified, name, description) VALUES (now(), now(), 'MASTER', 'MASTER HEARING ON BEHALF OF A CLIENT')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO hearing_type (created, modified, name, description) VALUES (now(), now(), 'MERIT', 'MERIT HEARING ON BEHALF OF A CLIENT')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO task_type (created, modified, name, description) VALUES (now(), now(), 'DUE AT HEARING', 'DUE AT HEARING')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO task_type (created, modified, name, description) VALUES (now(), now(), 'DOCUMENT PREPARATION', 'EVIDENCE COLLECTION AND PREPARATION')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO court (created, modified, name, street_address, city, state, zip_code, phone_number, status) VALUES (now(), now(), 'DALLAS IMMIGRATION COURT', '1100 COMMERCE STREET, SUITE 1060', 'DALLAS', 'TX', '75242', '2147671814', 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO court (created, modified, name, street_address, city, state, zip_code, phone_number, status) VALUES (now(), now(), 'PHOENIX IMMIGRATION COURT', '250 N. SEVENTH AVE., SUITE 300', 'PHOENIX', 'AZ', '85007', '6026402747', 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO judge (created, modified, name, webex, court_id, status) VALUES (now(), now(), 'E. MARK BARCUS (EMB), ACIJ', 'HTTPS://EOIR.WEBEX.COM/MEET/ACIJ.BARCUS ', 1, 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO judge (created, modified, name, webex, court_id, status) VALUES (now(), now(), 'SARAH ELLISON (SME)', 'HTTPS://EOIR.WEBEX.COM/JOIN/IJ.ELLISON ', 1, 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO judge (created, modified, name, webex, court_id, status) VALUES (now(), now(), 'IRENE C. FELDMAN (ICF), ACIJ', 'HTTPS://EOIR.WEBEX.COM/MEET/ACIJ.FELDMAN', 2, 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO judge (created, modified, name, webex, court_id, status) VALUES (now(), now(), 'MUNISH SHARDA (MS1)', 'HTTPS://EOIR.WEBEX.COM/MEET/IJ.SHARDA', 2, 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO client (created, modified, name, a_number, email, phone_number, judge_id, status) VALUES (now(), now(), 'MISTER SMITH', '203040506', 'MISTERSMITH@JOHNDOE.COM', '4445556669',  4, 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO client (created, modified, name, email, phone_number, status) VALUES (now(), now(), 'JANE DOE', 'JANEDOE@MRSSMITH.COM', '9993336660', 'ACTIVE')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO court_case (created, modified, case_type_id, client_id, status) VALUES (now(), now(), 1, 1, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO court_case (created, modified, case_type_id, client_id, status) VALUES (now(), now(), 2, 2, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO form (created, modified, form_type_id, court_case_id, status) VALUES (now(), now(), 1, 1, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO form (created, modified, form_type_id, court_case_id, status) VALUES (now(), now(), 2, 2, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO hearing_calendar (created, modified, hearing_date, hearing_type_id, court_case_id, status) VALUES (now(), now(), '2024-04-30 06:00:00', 1, 1, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO hearing_calendar (created, modified, hearing_date, hearing_type_id, court_case_id, status) VALUES (now(), now(), '2024-04-30 06:00:00', 2, 2, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO task_calendar (created, modified, task_date, due_date, task_type_id, hearing_calendar_id, form_id, status) VALUES (now(), now(), '2024-03-31 06:00:00', '2024-03-31 06:00:00', 1, 1, NULL, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO task_calendar (created, modified, task_date, due_date, task_type_id, hearing_calendar_id, form_id, status) VALUES (now(), now(), '2024-03-31 06:00:00', '2024-03-31 06:00:00', 1, 2, NULL, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO task_calendar (created, modified, task_date, due_date, task_type_id, hearing_calendar_id, form_id, status) VALUES (now(), now(), '2024-02-27 06:00:00', '2024-02-29 06:00:00', 2, NULL, 1, 'OPEN')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO task_calendar (created, modified, task_date, due_date, task_type_id, hearing_calendar_id, form_id, status) VALUES (now(), now(), '2024-02-28 06:00:00', '2024-02-29 06:00:00', 2, NULL, 2, 'OPEN')"""  # noqa: E501
    )

    op.execute(
        """INSERT INTO case_collection (created, modified, quote_amount, court_case_id, status) VALUES (now(), now(), 10000.00, 1, 'CREATED')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO case_collection (created, modified, quote_amount, court_case_id, status) VALUES (now(), now(), 10000.00, 2, 'CREATED')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO cash_collection (created, modified, collection_date, collected_amount, waived_amount, memo, case_collection_id, collection_method_id, status) VALUES (now(), now(), '2024-02-13 06:00:00', 250.00, -1.00, 'ZELLE TRF TO ACCOUNT# 9372' 1, 1, 'RECEIVED')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO cash_collection (created, modified, collection_date, collected_amount, waived_amount, memo, case_collection_id, collection_method_id, status) VALUES (now(), now(), '2024-02-21 06:00:00', 1000.00, -1.00, 'CHECK BOFA # 1001' 1, 3, 'RECEIVED')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO cash_collection (created, modified, collection_date, collected_amount, waived_amount, memo, case_collection_id, collection_method_id, status) VALUES (now(), now(), '2024-02-14 06:00:00', 700.00, -1.00, 'MONEY ORDER #44854' 2, 2, 'RECEIVED')"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO cash_collection (created, modified, collection_date, collected_amount, waived_amount, memo, case_collection_id, collection_method_id, status) VALUES (now(), now(), '2024-02-22 06:00:00', 500.00, -1.00, 'HANDED CASH TO JOHN' 2, 4, 'RECEIVED')"""  # noqa: E501
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("history_court_court_id", "history_court")
    op.drop_constraint("judge_court_id", "judge")
    op.drop_constraint("client_judge_id", "client")
    op.drop_constraint("history_judge_judge_id", "history_judge")
    op.drop_constraint("history_judge_court_id", "history_judge")
    op.drop_constraint("court_case_client_id", "court_case")
    op.drop_constraint("court_case_case_type_id", "court_case")
    op.drop_constraint("history_client_judge_id", "history_client")
    op.drop_constraint("history_client_client_id", "history_client")
    op.drop_constraint("case_collection_court_case_id", "case_collection")
    op.drop_constraint("form_form_type_id", "form")
    op.drop_constraint("form_court_case_id", "form")
    op.drop_constraint("hearing_calendar_hearing_type_id", "hearing_calendar")
    op.drop_constraint("hearing_calendar_court_case_id", "hearing_calendar")
    op.drop_constraint("history_court_case_court_case_id", "history_court_case")
    op.drop_constraint("history_court_case_client_id", "history_court_case")
    op.drop_constraint("history_court_case_case_type_id", "history_court_case")
    op.drop_constraint("cash_collection_collection_method_id", "cash_collection")
    op.drop_constraint("cash_collection_case_collection_id", "cash_collection")
    op.drop_constraint(
        "history_case_collection_case_collection_id", "history_case_collection"
    )
    op.drop_constraint(
        "history_case_collection_court_case_id", "history_case_collection"
    )
    op.drop_constraint(
        "history_hearing_calendar_hearing_type_id", "history_hearing_calendar"
    )
    op.drop_constraint(
        "history_hearing_calendar_hearing_calendar_id", "history_hearing_calendar"
    )
    op.drop_constraint(
        "history_hearing_calendar_court_case_id", "history_hearing_calendar"
    )
    op.drop_constraint("task_calendar_task_type_id", "task_calendar")
    op.drop_constraint("task_calendar_hearing_calendar_id", "task_calendar")
    op.drop_constraint("task_calendar_form_id", "task_calendar")
    # op.drop_constraint("task_calendar_hearing_calendar_id_1", "task_calendar")
    # op.drop_constraint("task_calendar_form_id_1", "task_calendar")
    op.drop_constraint(
        "history_cash_collection_case_collection_id", "history_cash_collection"
    )
    op.drop_constraint(
        "history_cash_collection_cash_collection_id", "history_cash_collection"
    )
    op.drop_constraint(
        "history_cash_collection_collection_method_id", "history_cash_collection"
    )
    op.drop_constraint("history_form_task_calendar_id", "history_form")
    op.drop_constraint("history_form_form_type_id", "history_form")
    op.drop_constraint("history_form_form_id", "history_form")
    op.drop_constraint("history_form_court_case_id", "history_form")
    op.drop_constraint("history_task_calendar_task_type_id", "history_task_calendar")
    op.drop_constraint(
        "history_task_calendar_task_calendar_id", "history_task_calendar"
    )
    op.drop_constraint(
        "history_task_calendar_hearing_calendar_id", "history_task_calendar"
    )
    op.drop_constraint("history_task_calendar_form_id", "history_task_calendar")
    op.drop_table("history_task_calendar")
    op.drop_table("history_form")
    op.drop_table("history_cash_collection")
    op.drop_table("task_calendar")
    op.drop_table("history_hearing_calendar")
    op.drop_table("history_case_collection")
    op.drop_table("cash_collection")
    op.drop_table("history_court_case")
    op.drop_table("hearing_calendar")
    op.drop_table("form")
    op.drop_table("case_collection")
    op.drop_table("history_client")
    op.drop_table("court_case")
    op.drop_table("history_judge")
    op.drop_table("client")
    op.drop_table("judge")
    op.drop_table("history_court")
    op.drop_table("task_type")
    op.drop_table("hearing_type")
    op.drop_table("form_type")
    op.drop_table("court")
    op.drop_table("collection_method")
    op.drop_table("case_type")
    # ### end Alembic commands ###
