"""fifth

Revision ID: b6fd706c5798
Revises: c61b6bbb3dd2
Create Date: 2023-12-19 22:14:23.662692

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6fd706c5798"
down_revision: Union[str, None] = "c61b6bbb3dd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "history_case_collection",
        "quote_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "history_case_collection",
        "quote_amount",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.alter_column(
        "history_case_collection",
        "initial_payment",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.alter_column(
        "history_case_collection",
        "collection_method_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "history_case_collection",
        "court_case_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "collection_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "collected_amount",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "waived_amount",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "case_collection_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "history_cash_collection",
        "collection_method_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "history_client", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "history_court", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "history_court_case", "case_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "history_court_case", "client_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "history_form", "form_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "history_form", "form_status_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "history_form", "court_case_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "history_hearing_calendar",
        "hearing_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "history_hearing_calendar",
        "hearing_type_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "history_hearing_calendar",
        "court_case_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "history_judge", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "history_judge", "court_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "history_task_calendar",
        "task_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "history_task_calendar",
        "task_type_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "history_task_calendar",
        "court_case_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "history_task_calendar",
        "court_case_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_task_calendar",
        "task_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_task_calendar",
        "task_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "history_judge", "court_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "history_judge", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "history_hearing_calendar",
        "court_case_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_hearing_calendar",
        "hearing_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_hearing_calendar",
        "hearing_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "history_form", "court_case_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "history_form", "form_status_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "history_form", "form_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "history_court_case", "client_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "history_court_case", "case_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "history_court", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "history_client", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "history_cash_collection",
        "collection_method_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_cash_collection",
        "case_collection_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_cash_collection",
        "waived_amount",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "history_cash_collection",
        "collected_amount",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "history_cash_collection",
        "collection_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "history_case_collection",
        "court_case_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_case_collection",
        "collection_method_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "history_case_collection",
        "initial_payment",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "history_case_collection",
        "quote_amount",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "history_case_collection",
        "quote_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###
