"""fourth

Revision ID: c61b6bbb3dd2
Revises: 7e7707fe5725
Create Date: 2023-12-10 21:24:18.985503

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c61b6bbb3dd2"
down_revision: Union[str, None] = "7e7707fe5725"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
