"""first

Revision ID: e8011800626b
Revises:
Create Date: 2024-02-28 23:24:13.217557

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8011800626b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_permission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "app_role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "case_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "collection_method",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "component_status",
        sa.Column("component_name", sa.String(length=100), nullable=False),
        sa.Column("status_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "component_name", "status_name", name="component_status_component_status_id"
        ),
    )
    op.create_table(
        "filing_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "hearing_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "task_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "app_role_permission",
        sa.Column("app_role_id", sa.Integer(), nullable=False),
        sa.Column("app_permission_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_permission_id"],
            ["app_permission.id"],
            name="app_role_permission_app_permission_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["app_role_id"],
            ["app_role.id"],
            name="app_role_permission_app_role_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app_user",
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("password", sa.String(length=250), nullable=False),
        sa.Column("full_name", sa.String(length=250), nullable=False),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("is_validated", sa.Boolean, nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="app_user_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "court",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("dhs_address", sa.String(length=1000), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="court_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "app_user_role",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("app_role_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_role_id"],
            ["app_role.id"],
            name="app_user_role_app_role_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="app_user_role_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_court",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("court_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("dhs_address", sa.String(length=1000), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_court_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_court_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["court.id"],
            name="history_court_court_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "judge",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("webex", sa.String(length=1000), nullable=True),
        sa.Column("court_id", sa.Integer(), nullable=False),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="judge_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["court.id"],
            name="judge_court_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("webex"),
    )
    op.create_table(
        "client",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("a_number", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("judge_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="client_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["judge_id"],
            ["judge.id"],
            name="client_judge_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("a_number"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "history_judge",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("webex", sa.String(length=1000), nullable=True),
        sa.Column("court_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_judge_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_judge_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["court.id"],
            name="history_judge_court_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["judge_id"],
            ["judge.id"],
            name="history_judge_judge_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "court_case",
        sa.Column("case_type_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_type_id"],
            ["case_type.id"],
            name="court_case_case_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name="court_case_client_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="court_case_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_type_id", "client_id", name="court_case_case_type_client_id"
        ),
    )
    op.create_table(
        "history_client",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("a_number", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("judge_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_client_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name="history_client_client_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_client_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["judge_id"],
            ["judge.id"],
            name="history_client_judge_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "case_collection",
        sa.Column("quote_amount", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="case_collection_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="case_collection_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("court_case_id"),
    )
    op.create_table(
        "filing",
        sa.Column("submit_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_number", sa.String(length=100), nullable=True),
        sa.Column("priority_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_submit_date", sa.DateTime(), nullable=True),
        sa.Column("decision_date", sa.DateTime(), nullable=True),
        sa.Column("filing_type_id", sa.Integer(), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="filing_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="filing_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["filing_type_id"],
            ["filing_type.id"],
            name="filing_filing_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hearing_calendar",
        sa.Column("hearing_date", sa.DateTime(), nullable=False),
        sa.Column("hearing_type_id", sa.Integer(), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="hearing_calendar_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="hearing_calendar_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_type_id"],
            ["hearing_type.id"],
            name="hearing_calendar_hearing_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("court_case_id"),
    )
    op.create_table(
        "history_court_case",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("court_case_id", sa.Integer(), nullable=False),
        sa.Column("case_type_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_court_case_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_type_id"],
            ["case_type.id"],
            name="history_court_case_case_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name="history_court_case_client_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_court_case_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_court_case_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cash_collection",
        sa.Column("collection_date", sa.DateTime(), nullable=False),
        sa.Column("collected_amount", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("waived_amount", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("memo", sa.String(length=3000), nullable=False),
        sa.Column("case_collection_id", sa.Integer(), nullable=False),
        sa.Column("collection_method_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_collection_id"],
            ["case_collection.id"],
            name="cash_collection_case_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_method_id"],
            ["collection_method.id"],
            name="cash_collection_collection_method_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_case_collection",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("case_collection_id", sa.Integer(), nullable=False),
        sa.Column("quote_amount", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("court_case_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_case_collection_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_collection_id"],
            ["case_collection.id"],
            name="history_case_collection_case_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_case_collection_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_case_collection_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_hearing_calendar",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("hearing_calendar_id", sa.Integer(), nullable=False),
        sa.Column("hearing_date", sa.DateTime(), nullable=True),
        sa.Column("hearing_type_id", sa.Integer(), nullable=True),
        sa.Column("court_case_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_hearing_calendar_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_hearing_calendar_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_hearing_calendar_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_calendar_id"],
            ["hearing_calendar.id"],
            name="history_hearing_calendar_hearing_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_type_id"],
            ["hearing_type.id"],
            name="history_hearing_calendar_hearing_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_calendar",
        sa.Column("task_date", sa.DateTime(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("task_type_id", sa.Integer(), nullable=False),
        sa.Column("hearing_calendar_id", sa.Integer(), nullable=True),
        sa.Column("filing_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="task_calendar_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"],
            ["filing.id"],
            name="task_calendar_filing_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_calendar_id"],
            ["hearing_calendar.id"],
            name="task_calendar_hearing_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"],
            ["task_type.id"],
            name="task_calendar_task_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_cash_collection",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("cash_collection_id", sa.Integer(), nullable=False),
        sa.Column("collection_date", sa.DateTime(), nullable=True),
        sa.Column("collected_amount", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("waived_amount", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("memo", sa.String(length=3000), nullable=True),
        sa.Column("case_collection_id", sa.Integer(), nullable=True),
        sa.Column("collection_method_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_cash_collection_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_collection_id"],
            ["case_collection.id"],
            name="history_cash_collection_case_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cash_collection_id"],
            ["cash_collection.id"],
            name="history_cash_collection_cash_collection_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_method_id"],
            ["collection_method.id"],
            name="history_cash_collection_collection_method_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_filing",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("filing_id", sa.Integer(), nullable=False),
        sa.Column("submit_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_date", sa.DateTime(), nullable=True),
        sa.Column("receipt_number", sa.String(length=100), nullable=True),
        sa.Column("priority_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_date", sa.DateTime(), nullable=True),
        sa.Column("rfe_submit_date", sa.DateTime(), nullable=True),
        sa.Column("decision_date", sa.DateTime(), nullable=True),
        sa.Column("filing_type_id", sa.Integer(), nullable=True),
        sa.Column("court_case_id", sa.Integer(), nullable=True),
        sa.Column("task_calendar_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_filing_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_filing_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["court_case_id"],
            ["court_case.id"],
            name="history_filing_court_case_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"],
            ["filing.id"],
            name="history_filing_filing_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["filing_type_id"],
            ["filing_type.id"],
            name="history_filing_filing_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_calendar_id"],
            ["task_calendar.id"],
            name="history_filing_task_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_task_calendar",
        sa.Column("app_user_id", sa.Integer(), nullable=False),
        sa.Column("task_calendar_id", sa.Integer(), nullable=False),
        sa.Column("task_date", sa.DateTime(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("task_type_id", sa.Integer(), nullable=True),
        sa.Column("hearing_calendar_id", sa.Integer(), nullable=True),
        sa.Column("filing_id", sa.Integer(), nullable=True),
        sa.Column("component_status_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=10000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
            name="history_task_calendar_app_user_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_status_id"],
            ["component_status.id"],
            name="history_task_calendar_component_status_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"],
            ["filing.id"],
            name="history_task_calendar_filing_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hearing_calendar_id"],
            ["hearing_calendar.id"],
            name="history_task_calendar_hearing_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_calendar_id"],
            ["task_calendar.id"],
            name="history_task_calendar_task_calendar_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"],
            ["task_type.id"],
            name="history_task_calendar_task_type_id",
            onupdate="NO ACTION",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # other
    op.create_index(
        "task_calendar_hearing_calendar_id_1",
        "task_calendar",
        ["hearing_calendar_id"],
        unique=False,
        postgresql_where="(hearing_calendar_id IS NOT NULL)",
    )
    op.create_index(
        "task_calendar_filing_id_1",
        "task_calendar",
        ["filing_id"],
        unique=False,
        postgresql_where="(filing_id IS NOT NULL)",
    )
    op.execute(
        """INSERT INTO task_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'DUE AT HEARING', 'DUE AT HEARING', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO task_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'DOCUMENT PREP', 'DOCUMENT PREPARATION', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO hearing_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'MASTER', 'MASTER HEARING', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO hearing_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'MERITS', 'MERITS HEARING', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO case_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'ASYLUM', 'FILING ASYLUM WITH USCIS/BIA', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO case_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'TPS', 'FILING TPS WITH USCIS/BIA', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO filing_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'I-589', 'APPLICATION FOR ASYLUM AND FOR WITHHOLDING OF REMOVAL', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO filing_type (created, modified, name, description, is_deleted) VALUES (now(), now(), 'I-765', 'APPLICATION FOR EMPLOYMENT AUTHORIZATION', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description, is_deleted) VALUES (now(), now(), 'ZELLE', 'ZELLE TRANSFER', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description, is_deleted) VALUES (now(), now(), 'MONEY ORDER', 'MONEY ORDER', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CHECK', 'PERSONAL CHECK', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO collection_method (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CASH', 'CASH PAYMENT', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'APP_USERS', 'ACTIVE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'APP_USERS', 'INACTIVE', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'APP_USERS', 'DISABLED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COURTS', 'ACTIVE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COURTS', 'CLOSED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'JUDGES', 'ACTIVE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'JUDGES', 'RETIRED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'JUDGES', 'INACTIVE', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'CLIENTS', 'ACTIVE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'CLIENTS', 'INACTIVE', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COURT_CASES', 'ACTIVE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COURT_CASES', 'CLOSED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COURT_CASES', 'TRANSFERRED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'PENDING', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'RECEIVED', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'PROCESSING', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'SUBMITTED', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'EVIDENCE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'APPROVED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'DENIED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'FILINGS', 'WITHDRAWN', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'CALENDARS', 'DUE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'CALENDARS', 'DONE', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'CALENDARS', 'PAST_DUE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'CALENDARS', 'PAST_DONE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COLLECTIONS', 'PENDING', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COLLECTIONS', 'PAST_DUE', True, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COLLECTIONS', 'RECEIVED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO component_status (created, modified, component_name, status_name, is_active, is_deleted) VALUES (now(), now(), 'COLLECTIONS', 'WAIVED', False, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role (created, modified, name, description, is_deleted) VALUES (now(), now(), 'SUPERUSER', 'USER HAS ALL ACCESS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role (created, modified, name, description, is_deleted) VALUES (now(), now(), 'POWERUSER', 'USER HAS ACCESS TO ALL PARTS OF THE APP, REF TYPE VIEW ONLY', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role (created, modified, name, description, is_deleted) VALUES (now(), now(), 'STANDARD', 'USER HAS NO ACCESS TO REF DATA', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role (created, modified, name, description, is_deleted) VALUES (now(), now(), 'GUEST', 'USER HAS VIEW ONLY ACCESS, NO REF DATA ACCESS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURTS_CREATE', 'CAN ADD COURTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURTS_READ', 'CAN VIEW COURTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURTS_UPDATE', 'CAN UPDATE COURTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURTS_DELETE', 'CAN DELETE COURTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'JUDGES_CREATE', 'CAN ADD JUDGES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'JUDGES_READ', 'CAN VIEW JUDGES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'JUDGES_UPDATE', 'CAN UPDATE JUDGES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'JUDGES_DELETE', 'CAN DELETE JUDGES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CLIENTS_CREATE', 'CAN ADD CLIENTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CLIENTS_READ', 'CAN VIEW CLIENTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CLIENTS_UPDATE', 'CAN UPDATE CLIENTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CLIENTS_DELETE', 'CAN DELETE CLIENTS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURT_CASES_CREATE', 'CAN ADD COURT CASES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURT_CASES_READ', 'CAN VIDE COURT CASES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURT_CASES_UPDATE', 'CAN UPDATE COURT CASES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COURT_CASES_DELETE', 'CAN DELETE COURT CASES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'FILINGS_CREATE', 'CAN ADD FILINGS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'FILINGS_READ', 'CAN VIEW FILINGS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'FILINGS_UPDATE', 'CAN UPDATE FILINGS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'FILINGS_DELETE', 'CAN DELETE FILINGS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CALENDARS_CREATE', 'CAN ADD CALENDARS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CALENDARS_READ', 'CAN VIEW CALENDARS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CALENDARS_UPDATE', 'CAN UPDATE CALENDARS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'CALENDARS_DELETE', 'CAN DELETE CALENDARS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COLLECTIONS_CREATE', 'CAN ADD COLLECTIONS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COLLECTIONS_READ', 'CAN VIEW COLLECTIONS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COLLECTIONS_UPDATE', 'CAN UPDATE COLLECTIONS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'COLLECTIONS_DELETE', 'CAN DELETE COLLECTIONS', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'REF_TYPES_CREATE', 'CAN ADD REF TYPES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'REF_TYPES_READ', 'CAN VIEW REF TYPES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'REF_TYPES_UPDATE', 'CAN UPDATE REF TYPES', False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_permission (created, modified, name, description, is_deleted) VALUES (now(), now(), 'REF_TYPES_DELETE', 'CAN DELETE REF TYPES', False)"""  # noqa: E501
    )

    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 4, 2, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 4, 6, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 4, 10, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 4, 14, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 4, 18, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 4, 22, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 4, 26, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 1, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 2, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 3, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 5, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 6, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 7, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 9, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 10, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 11, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 13, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 14, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 15, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 17, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 18, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 19, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 21, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 22, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 23, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 25, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 26, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 3, 27, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 1, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 2, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 3, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 4, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 5, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 6, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 7, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 8, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 9, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 10, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 11, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 12, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 13, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 14, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 15, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 16, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 17, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 18, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 19, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 20, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 21, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 22, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 23, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 24, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 25, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 26, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 27, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 28, False)"""  # noqa: E501
    )
    op.execute(
        """INSERT INTO app_role_permission (created, modified, app_role_id, app_permission_id, is_deleted) VALUES (now(), now(), 2, 30, False)"""  # noqa: E501
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("history_task_calendar")
    op.drop_table("history_filing")
    op.drop_table("history_cash_collection")
    op.drop_table("task_calendar")
    op.drop_table("history_hearing_calendar")
    op.drop_table("history_case_collection")
    op.drop_table("cash_collection")
    op.drop_table("history_court_case")
    op.drop_table("hearing_calendar")
    op.drop_table("filing")
    op.drop_table("case_collection")
    op.drop_table("history_client")
    op.drop_table("court_case")
    op.drop_table("history_judge")
    op.drop_table("client")
    op.drop_table("judge")
    op.drop_table("history_court")
    op.drop_table("app_user_role")
    op.drop_table("court")
    op.drop_table("app_user")
    op.drop_table("app_role_permission")
    op.drop_table("task_type")
    op.drop_table("hearing_type")
    op.drop_table("filing_type")
    op.drop_table("component_status")
    op.drop_table("collection_method")
    op.drop_table("case_type")
    op.drop_table("app_role")
    op.drop_table("app_permission")
    # ### end Alembic commands ###
