"""Third

Revision ID: f9bec2b3cff3
Revises: a58b1f2379f9
Create Date: 2023-09-23 23:07:19.671908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9bec2b3cff3'
down_revision: Union[str, None] = 'a58b1f2379f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_collection', sa.Column('waived_amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_collection', 'waived_amount')
    # ### end Alembic commands ###
